version: "3"
services:
  api:
    # build: . # docker-compose.ymlはgo/直下に置いてるので、ディレクトリでビルドする
    image: echo_image
    container_name: api
    ports:
      - 1323:1323
    depends_on: # dbコンテナに接続。ビルドするのもdbコンテナが立ち上がってからになる
      - db
  db:
    image: db_image
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go_trial
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    volumes:
      # 左ホスト:右コンテナ
      - mysql_data:/var/lib/mysql #ここで .mysql_dataとすると、Data Volumeでなくホストに直で保存された
      # - ./sqls/init:/docker-entrypoint-initdb.d
  web:
    image: web_image
    container_name: web
    ports:
      - "3000:3000"
    command: yarn dev
    volumes:
      - /usr/src/node_modules # Dockerfile内でyarn installしたnode_modulesを、そのまま残しておくため
      - ./web:/usr/src # /web内のファイルを変更すれば、ホットリロードされる
    environment:
      - NODE_ENV=development
volumes:
  mysql_data: # ローカルのディレクトリにデータを保存
