version: "3"
services:
  api:
    image: echo_image
    container_name: api
    ports:
      - 1323:1323
    depends_on:
      - db
  db:
    image: db_image
    container_name: db
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eng_quiz
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
  # web: 今後はおそらく使わない(Dockerネットワーク内だとlocalhostで名前解決できないので)
  #   image: web_image
  #   container_name: web
  #   ports:
  #     - "3000:3000"
  #   # command: yarn dev
  #   volumes:
  #     - /app/node_modules # Dockerfile内でyarn installしたnode_modulesを、そのまま残しておくため
  #     - ./web:/app # /web内のファイルを変更すれば、ホットリロードされる
  #   environment:
  #     - TODO_API_URL=http://localhost:1323/
volumes:
  mysql_data:
