apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 1323

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 14
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: takabunn/eng_quiz_echo_image:latest # echo_image
          imagePullPolicy: Always #Never
          ports:
            - containerPort: 1323
          env:
            - name: "DB_URL"
              value: "root:password@tcp(db-svc:3306)/eng_quiz?parseTime=true&loc=Asia%2FTokyo"
