apiVersion: v1
kind: Service
metadata:
  name: db # "mysql-master"
  labels:
    app: db # "mysql-master"
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: db # "mysql-master"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db # "mysql-master"
  labels:
    app: db # "mysql-master"
spec:
  serviceName: db # "mysql-master"
  selector:
    matchLabels:
      app: db # "mysql-master"
  replicas: 1
  template:
    metadata:
      labels:
        app: db # "mysql-master"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: db
          image: takabunn/eng_quiz_db_image:latest
          imagePullPolicy: Always # Never
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password" # ""不要？
            - name: MYSQL_DATABASE
              value: "eng_quiz" # ""不要？
            - name: TZ
              value: "Asia/Tokyo"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates: ##これにより、Podが要求するPVCをその度に作成する必要がなくなる
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ssd
        resources:
          requests:
            storage: 4Gi
