apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 3000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      # volumes: #静的アセット
      #   - name: assets
      #     emptyDir: {}
      containers:
        - name: web
          image: takabunn/eng_quiz_web_image:latest # web_image
          imagePullPolicy: Always # Never
          # lifecycle:
          #   postStart: # ①/distディレクトリにassetsファイルがコピーされる
          #     exec:
          #       command:
          #         - cp
          #         - -R
          #         - /web/.nuxt/dist
          #         - /
          ports:
            - containerPort: 3000
          env:
            - name: TODO_API_URL
              # value: 10.3.255.103:1323 # エラーが出るまでに時間がかかる(が失敗)
              # value: api # → ERR_NAME_NOT_RESOLVED
              value: api:1323 # → ERR_NAME_NOT_RESOLVED
              # value: "api:1323" #こっちはダメっぽい？
          # volumeMounts:
          #   - mountPath: /dist # ②nginx側の/var/www/_nuxtと、web側の/distをマウント。webの/distの内容を、nginx-nuxtへコピー
          #     name: assets
