apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: default
  labels:
    app: web
    type: frontend
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 3000
  selector:
    app: web
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 14
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: takabunn/eng_quiz_web_image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: TODO_API_URL
              value: http://api-svc:1323
